[package]
name = "cbuild"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
mlua = { workspace = true }
